import os

def download_coco_dataset():
    os.system('mkdir coco')
    os.system('cd coco')
    os.system('mkdir images')
    os.system('cd images')
    os.system('wget http://images.cocodataset.org/zips/train2017.zip')
    os.system('unzip -qq train2017.zip')
    os.system('rm train2017.zip')
    os.system('wget http://images.cocodataset.org/zips/val2017.zip')
    os.system('unzip -qq val2017.zip')
    os.system('rm val2017.zip')
    os.system('cd ..')
    os.system('wget http://images.cocodataset.org/annotations/annotations_trainval2017.zip')
    os.system('wget http://images.cocodataset.org/annotations/stuff_annotations_trainval2017.zip')
    os.system('unzip -qq annotations_trainval2017.zip')
    os.system('unzip -qq stuff_annotations_trainval2017.zip')
    os.system('rm annotations_trainval2017.zip')
    os.system('cd ..')